### ISSUE TITLE
Accessibility for Teams - Developers - Images - Confusing Text

### ISSUE THREAD

**Issue by jfc3-dol** [GSA/accessibility-for-teams#112]
On the  Developers images page ( https://accessibility.digital.gov/front-end/images/ ), there is confusing text related to the image ALT text that needs to be fixed, which is shown in the attached screenshot.

<img width="960" alt="digital dot gov - imges - Should not this be Alt Text or Alt Attribute since there are not Alt Tags" src="https://github.com/GSA/accessibility-for-teams/assets/10423487/08e38330-9050-4716-a3b8-332fe3a13460">

**Comment by ToniBonittoGSA** [comment]
Thank you! Fixed: https://github.com/GSA/accessibility-for-teams/pull/113
