### ISSUE TITLE
Write a README and CONTRIBUTING doc

### ISSUE THREAD

**Issue by maya** [GSA/accessibility-for-teams#20]
Write a README and CONTRIBUTING doc to explain: 

- [x] the purpose of this
- [x] how to contribute
- [x] what type of contributions we're looking for
  - Limited in scope
  - Has a demonstrable user need
  - Quick start guides, won't cover everything

/cc @jeremyzilar

**Comment by davidstenger** [comment]
https://docs.google.com/document/d/1p2t8C_b8JqwAGcTR1d5v63mwJXmQP6fI3fRJeTwpzV0/edit?usp=sharing
