### ISSUE TITLE
Colour contrast question

### ISSUE THREAD

**Issue by samsadasivan** [GSA/accessibility-for-teams#22]
![image](https://user-images.githubusercontent.com/16671230/42532208-2a97daf0-8454-11e8-89ee-409dddd80fbb.png)

Is it ok for iconography to not pass colour contrast ratio if there is a label associated with it? When should icons/charts be accessible?

**Comment by maya** [comment]
Hi @samsadasivan, thanks for your questions. WCAG 2.1 recommends using at least 3:1 color contrast which this meets: https://www.w3.org/TR/WCAG21/#non-text-contrast
<img width="720" alt="screen shot 2018-07-10 at 12 33 37 pm" src="https://user-images.githubusercontent.com/5249443/42533131-dcbaff3a-843d-11e8-9f9d-d07c8900e209.png">

The iconography is also non-text and meets the same color contrast requirements as above. For decorative graphics, it's OK to have empty or null alt text.

**Comment by cmaczo** [comment]
@Maya, my browser is showing the icons and borders as #9F8EF9 (same as @samsadasivan's). That's a 2.72:1 ratio. (Your ratio above was for #9983FC.)

**Comment by maya** [comment]
@cmaczo you're correct that #9F8EF9 is the color of the border, but the icon is #9983FC. Here's a link to the relevant line in the SVG file:

https://github.com/GSA/accessibility-for-teams/blob/8779c81e9a1feca0e7d698237f2344c73c1b3769/assets/img/icons/content.svg#L6

**Comment by maya** [comment]
To the original question, as stated in the link above, this is when you'd want to make sure you have at least 3:1 contrast:

>**User Interface Components**: Visual information required to identify user interface components and states, except for inactive components or where the appearance of the component is determined by the user agent and not modified by the author;
>
>**Graphical Objects**: Parts of graphics required to understand the content, except when a particular presentation of graphics is essential to the information being conveyed.

Since there's a label associated with it, it could be considered decorative, but it's nice to give it enough contrast in any case. Hope that helps!
