### ISSUE TITLE
incorrect terminology in "diverse users"

### ISSUE THREAD

**Issue by KSerra** [GSA/accessibility-for-teams#24]
Thanks for a great guide. First time filing an issue, hope I'm doing it right.

In the [diverse users](https://accessibility.digital.gov/product/diverse-users/) page of the product management section, the inclusion criteria uses non-standard terminology for gender. Currently it reads:

> Consider inclusion in your research and usability testing with people across a range of ages, races, locations, devices, interests, abilities, languages, English proficiency, gender orientations, and access to reliable internet.

Gender orientation isn't really a thing - what you probably meant was either [gender identity or sexual orientation](https://www.hrc.org/resources/sexual-orientation-and-gender-identity-terminology-and-definitions). To make the list inclusive, I would replacing "gender orientations," with "genders, sexual orientations,..." or just "genders" if you didn't mean to include sexual orientation (although it'd probably be good to include it!).

**Comment by maya** [comment]
Hi @KSerra, thanks for filing this issue. You are correct and that should be changed. Cross-referencing to our Code of Conduct, it looks like we use "gender identity." I think I will go with that as it seems it's the correct terminology as well.
