### ISSUE TITLE
What about researchers?

### ISSUE THREAD

**Issue by cmaczo** [GSA/accessibility-for-teams#26]
Hi friends,

Great work. I'm excited for all this has become.

Are you planning to introduce guidelines for UX researchers?
I know you mention it in the "product management" guide, but I think there's more to say.

I'd be a strong proponent because:
- In modern products, decisions get made based on research. If the research doesn't include people with disabilities, it's hard to make sure the product addresses their needs.
- Researchers often think of accessibility as a downstream "coding problem." You have an opportunity to encourage researchers to think about their responsibility for accessibility.
- Many people are theoretically committed to making sure their research includes a wide swath of users, but following through on it seems hard.

I think an entry for researchers could include tips for:
- recruiting folks using assistive technologies to participate in your research
- making research logistics friendly to people with various disabilities
- conducting interviews with people who can't hear or speak
- usability testing with screen reader users

Colin

**Comment by maya** [comment]
Hi @cmaczo, good to hear from you! 

Those are some great ideas and points! Were you able to take a look at the [UX design](https://accessibility.digital.gov/ux/getting-started/) guide. The first few pages touch on some of the points you bring up, including research. Going a bit deeper like you mention could be helpful too!

**Comment by cmaczo** [comment]
Yes, there's definitely some good encouragement in the UX design section. 

I think encouraging people to do these things is great. I think it's even better when we can explain *how* to do them. Working with people who use AT is foreign to many researchers (or people doing research) -- they're more likely to do it with more instruction.

I'd be happy to collaborate if y'all are open to PRs. :)

**Comment by maya** [comment]
We are open to PRs :) 

I think what you mentioned sounds really useful and would be happy to collaborate. Just today someone asked us about what companies there are for recruiting people with disabilities for usability testing that they can hire in government.

**Comment by nschonni** [comment]
Rather than companies, it might be good to look at how other companies are doing it themselves https://www.microsoft.com/en-us/diversity/inside-microsoft/cross-disability/hiring.aspx

PS: not saying that we're doing it better up north, just that I've liked what I've seen from their presentations at CSUN

**Comment by maya** [comment]
@nschonni Agree that doing it themselves sounds like a great solution for the longterm, but we can also provide practical solutions for the short term (e.g. hiring companies, etc...). 

@cmaczo were you thinking the UX researcher guidance would be a separate role from the UX designer or live within it?

For some context, we started this guide as an internal tool that was based on the roles we currently have at TTS, and UX designers at TTS also do research, while in other places outside of our organization UX researchers are a separate role, which may be why it feels like it's missing.

**Comment by maya** [comment]
Sounds good, I added a note to give context that the roles are based on the roles at TTS on the homepage.

**Comment by maya** [comment]
Hey @cmaczo! Still up for submitting a PR for this? Let us know how it's going + when you'll be able to share something.

**Comment by cmaczo** [comment]
Hey @Maya, this is going to have to be a long-term project for me. If you want to close the issue until I open a PR, that's fine with me.

**Comment by maya** [comment]
That works for me, feel free to give us a heads up when you work on this and we can open it back up.
