### ISSUE TITLE
QA Testing

### ISSUE THREAD

**Issue by michaelspellacy** [GSA/accessibility-for-teams#27]
Really great guide, but I feel that QA is a team that has been overlooked. Any plans to include that in the future? Keep up the good work!

**Comment by maya** [comment]
Hi @michaelspellacy, thanks for opening this issue! For some context, we started this guide as an internal tool that was based on the roles we currently have at TTS, and we don't have QA on our teams at the moment. But it would likely be a good role to add. Also, I think that most of the 508 Trusted Testers may already have a thorough checklist they follow.

**Comment by michaelspellacy** [comment]
Hi @maya! Thanks for your response and again, this resource.  It is wonderful. The reason I bring this up is that I have recently come to the realization, like yourselves, that in order for a company to be successful on the accessibility front, that *everybody* has to play a role in ensuring it. Many QA engineers often focus on usability for non-disabled users or think it is the front-end developers job to accommodate those with disabilities (at least where I work), when in reality, their testing should be a lot more inclusive. :-)

Perhaps I can assist in helping you flesh out a section for that!

**Comment by maya** [comment]
We'd be open to considering adding this in, but to be transparent this is a project of the Accessibility Guild, not our full-time project i.e. a side project for most of us at TTS, so we're limited in resources around adding new large features. If you'd like to begin by sketching out an outline, I think that would be a great start!

**Comment by maya** [comment]
Hi @michaelspellacy, just wanted to check in to see if you still had plans to flesh out this content or know when you'd be able to? If you need more time, we can close this issue until you have something ready.

**Comment by maya** [comment]
Haven't heard back on this, closing until we have more info / content submitted to us.
