### ISSUE TITLE
Browser Compatibility (IE and other browsers)

### ISSUE THREAD

**Issue by shahilmhd** [GSA/accessibility-for-teams#32]
Hello,

This is an awesome guide to all the developers. I appreciate if you could spend some time to enhance the browser compatibility including Internet Explorer 10+. I was just testing the application I could see some alignment issues. Although the site looks great. We need to give some soft touch to make it consistent and responsive across all the digital devices. I think together as a team we can override the issue. I would love to contribute in terms of UI/UX. Let me know if I am helpful. 

**Thanks**,
Shahil
UI/UX Designer/Developer

**Comment by maya** [comment]
Thanks for reaching out to us, @shahilmhd. We follow the [2% rule around browser support](https://designsystem.digital.gov/getting-started/developers/#browser-support), and support IE 11 and above so will not be prioritizing support below. We don't believe that it must look exactly the same across browsers. That said, if a fix is reasonable and small, we may consider it. Thanks!
