### ISSUE TITLE
Request: Closed captioning for video/multimedia content section?

### ISSUE THREAD

**Issue by jaredcunha** [GSA/accessibility-for-teams#33]
I love this project! This site is so easy to digest and share across teams!

I'm wondering if you all had any thoughts about adding a section about using closed captioning on multimedia content for hearing-impaired users, perhaps in the Content section?

**Comment by maya** [comment]
Thanks @jaredcunha! That sounds like a reasonable idea. Would you like to have a go at writing the content?

**Comment by jaredcunha** [comment]
@maya Absolutely!

**Comment by maya** [comment]
@jaredcunha also, are you able to share a little context around this section? How does video captioning come up in your project work? Thanks!

**Comment by jaredcunha** [comment]
@maya This hasn't actually come up on any current projects of mine, but a future one perhaps. I'm working on a new website for USDS and it looks like we're going to place a video, so maybe that will be my chance? By the way, I'm setting that up with the new V2 of the USWDS, so I can let you know how that goes (off-topic, I know!). 

I just noticed that there wasn't anything on the site for hearing-impaired users and thought it'd be helpful to include. It's sites like this that make it easy it for us to point stakeholders to whenever accessibility issues come up, like the way the USWDS gets us past most debates over aesthetics.

**Comment by maya** [comment]
Thanks for that background!

Re: USWDS 2.0 that's awesome to hear! Feel free to reach out to use to let us know how it goes (uswds@gsa.gov), on Slack https://chat.18f.gov/ or we can set up a shared Slack channel, or on GitHub https://github.com/uswds/uswds/issues.

**Comment by maya** [comment]
Done in #37, #38.
