### ISSUE TITLE
Accessibility for Teams--adding Audio Description

### ISSUE THREAD

**Issue by MRHart03** [GSA/accessibility-for-teams#40]
Please consider adding Audio Description under the Video and Multimedia section of the Accessibility for Teams guide. Captions and transcript information is provided, but not audio description--a Section 508 requirement. 

There are lots of resources. Here's one that I was involved with: https://www.doi.gov/employees/creativecomms/audio-description-introduction-core-concepts

There are others. If I can provide any information or assistance, please let me know.

Thanks so much!--Michele

**Comment by nkkl** [comment]
@maya @davidstenger this seems like a good thing to add, and should (hopefully) be a microcopy change. Thoughts?

**Comment by maya** [comment]
Yes, should be fine to add. If someone wants to get started and write the content, we can add it in. Looking for around 1 bullet point worth of content to explain it, in the style of the rest of the page.

**Comment by davidstenger** [comment]
@nkkl @maya Thoughts?Audio description is required when important information is visually shown on the screen that cannot be observed by a blind or vision-impaired individual.
