### ISSUE TITLE
Broken Link to Federalist in Footer

### ISSUE THREAD

**Issue by brickman1444** [GSA/accessibility-for-teams#69]
On https://accessibility.digital.gov/ if you click the  link in the footer text "This website is hosted on Federalist." the link will take you to https://federalist.fr.cloud.gov/ which returns "404 Not Found: Requested route ('federalist.fr.cloud.gov') does not exist."

I can see https://federalist.18f.gov/ returns a successful website, so maybe the link intends to go there instead.

I ran into this bug in Chrome on Android.

Is this a wider bug that affects more sites? Should I report this somewhere else?

**Comment by ToniBonittoGSA** [comment]
Appears to be working now. Thanks for submitting this.
