### ISSUE TITLE
UX Inclusive Design Page Broken Link

### ISSUE THREAD

**Issue by jfc3-dol** [GSA/accessibility-for-teams#71]
On the" UX Inclusive Design" page ( https://accessibility.digital.gov/ux/inclusive-design/ ), the "Microsoft’s Inclusive Design Manual" link gets redirected. I think the link should be the one listed below, but I'm not sure where it used to point.

https://accessibility.digital.gov/ux/inclusive-design/

**Comment by ToniBonittoGSA** [comment]
On https://digital.gov/resources/introduction-accessibility/ we have

> [Microsoft’s Inclusive Design Toolkit](https://download.microsoft.com/download/b/0/d/b0d4bf87-09ce-4417-8f28-d60703d672ed/inclusive_toolkit_manual_final.pdf) (PDF, 22 MB, 32 pages) — An approachable introduction to the history and principles of inclusive design ([they also have a full site about Inclusive Design](https://www.microsoft.com/design/inclusive/)).

**Comment by iamjolly** [comment]
Thanks for this! Microsoft must have slightly changed their URLs, so those suggested resources seem like a good update to make. Thanks @jfc3-dol and @ToniBonittoGSA!

👋  John! Good to hear from you. :)
