### ISSUE TITLE
 Humanize Accessibility Page Broken Link

### ISSUE THREAD

**Issue by jfc3-dol** [GSA/accessibility-for-teams#72]
On the "Humanize Accessibility" page ( https://accessibility.digital.gov/ux/humanize-accessibility/ ) the link "accessibility issues in your personas" to Anne Gibson's "An Alphabet of Accessibility Issues" article ( https://the-pastry-box-project.net/anne-gibson/2014-july-31 ) looks to no longer be available.

**Comment by ToniBonittoGSA** [comment]
That article page (and the site itself) has a maintenance notice in French; translated: 

> In order to improve its performance, this site is currently under maintenance.
> Thank you for understanding.

I found her [blog](https://www.theinterconnected.net/), but it only mentions the article a few times; does not provide a copy of it.
Will be up to the Accessibility Guild to decide if/when to remove this link.

**Comment by iamjolly** [comment]
thank you @jfc3-dol for spotting this. I believe I've found where the author's article lives on her own site.
