### ISSUE TITLE
Broken Link on the UX Navigation Shortcuts Page

### ISSUE THREAD

**Issue by jfc3-dol** [GSA/accessibility-for-teams#73]
On the UX Navigation Shortcuts Page ( https://accessibility.digital.gov/ux/navigation-shortcuts/ ), the "should become visible when it has focus" link points to a wrong or changed the in-page anchor link and probably should be the following link https://webaim.org/techniques/skipnav/#hidden instead of https://webaim.org/techniques/skipnav/#invisible.

**Comment by ToniBonittoGSA** [comment]
Thank you

Change link in last sentence of second bullet to

> * Include a “Skip to main content” link before the header for keyboard users. Keyboard users can’t take advantage of landmark navigation so a skip link helps them navigate more quickly. This link can be visually hidden but [should become visible when it has focus](https://webaim.org/techniques/skipnav/#hidden).

**Comment by ToniBonittoGSA** [comment]
https://github.com/GSA/accessibility-for-teams/pull/77
