### ISSUE TITLE
Confusing Text on the UX Images Page

### ISSUE THREAD

**Issue by jfc3-dol** [GSA/accessibility-for-teams#74]
On the "UX Images" page ( https://accessibility.digital.gov/ux/images/ ) the text "...work with your front end designer to make sure they’re coded correctly." is confusing.

Shouldn't it be "...work with your front end **developer** to make sure they’re coded correctly." since developers are most likely making coding changes and not "designers"?

**Comment by ToniBonittoGSA** [comment]
Thank you.

First bullet on page:

> * Images that are purely decorative shouldn’t be announced by the screenreader, work with your front end designer to make sure they’re coded correctly.

Change to:

> * Images that are purely decorative shouldn’t be announced by the screenreader, work with your front-end developer to make sure they’re coded correctly.

**Comment by ToniBonittoGSA** [comment]
https://github.com/GSA/accessibility-for-teams/pull/79

**Comment by ToniBonittoGSA** [comment]
https://github.com/GSA/accessibility-for-teams/pull/79
