### ISSUE TITLE
Redirected Link on the Visual Design Typography Page

### ISSUE THREAD

**Issue by jfc3-dol** [GSA/accessibility-for-teams#75]
On the Visual Design Typography page ( https://accessibility.digital.gov/visual-design/typography/ ), the link "U.S. Web Design Standards" gets redirected to the following link https://designsystem.digital.gov/components/typography/.

**Comment by ToniBonittoGSA** [comment]
The redirect is correct, but it should probably be updated to link to a specific section of that page.

Suggestion: 

> * For an easy place to get started, the [U.S. Web Design Standards](https://designsystem.digital.gov/) (USWDS) [Typography page](https://designsystem.digital.gov/components/typography/) includes a set of [open source typeface recommendations](https://designsystem.digital.gov/components/typography/#included-typefaces) that emphasize legibility.

**Comment by ToniBonittoGSA** [comment]
https://github.com/GSA/accessibility-for-teams/pull/78
