### ISSUE TITLE
Broken on the Visual Design Forms Page

### ISSUE THREAD

**Issue by jfc3-dol** [GSA/accessibility-for-teams#76]
On the Visual Design Forms Page ( https://accessibility.digital.gov/visual-design/forms/ ), the "GOV.UK elements: Form elements" link ( https://govuk-elements.herokuapp.com/form-elements ) is now broken.

**Comment by ToniBonittoGSA** [comment]
The link is not broken; it loads -- they just use something else now. There is now a note explaining the change at the top of that Form Elements page.

Accessibility for Teams folks will have to decide on how to update the copy:

> Resources
> * [GOV.UK elements: Form elements](http://govuk-elements.herokuapp.com/form-elements)
