### ISSUE TITLE
Simplify SASS structure

### ISSUE THREAD

**Issue by mejiaj** [GSA/accessibility-for-teams#99]
Now that we're using [uswds-compile PR#95](https://github.com/GSA/accessibility-for-teams/pull/95). We should simplify the SASS structure to only include USWDS theme settings files.

This means the directories and their children in `stylesheets/lib/uswds-sass` are no longer needed.

We can also remove these custom SASS tasks in gulpfile.js and rely on the USWDS-Compile defaults.
https://github.com/GSA/accessibility-for-teams/blob/045cce18544dfa92f3fa3424de8cd901fbd21c7c/gulpfile.js#L54-L70

**Comment by nick-mon1** [comment]
Resolved by #100
